*TO DO*
- one hot na Y, four g, wifi
- skalowanie?
- model

In [3]:
import pandas as pd
import keras
import sklearn as sk
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Wczytanie danych

In [5]:
phone_data = pd.read_csv("dataset.csv")

In [6]:
phone_data.head()

,Unnamed: 0,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,0,842,no,2.2,0,1,no,7,0.6,188,...,20,756,2549.0,9,7,19.0,0,0,wifi,medium cost
1,1,1021,yes,0.5,1,0,yes,53,0.7,136,...,905,1988,2631.0,17,3,7.0,1,1,no_wifi,high cost
2,2,563,yes,0.5,1,2,yes,41,0.9,145,...,1263,1716,2603.0,11,2,9.0,1,1,no_wifi,high cost
3,3,615,yes,2.5,0,0,no,10,0.8,131,...,1216,1786,2769.0,16,8,11.0,1,0,no_wifi,high cost
4,4,1821,yes,1.2,0,13,yes,44,0.6,141,...,1208,1212,1411.0,8,2,15.0,1,1,no_wifi,medium cost

In [10]:
phone_data['price_range'].value_counts()

price_range
low cost          485
high cost         484
medium cost       483
very high cost    483
Name: count, dtype: int64

In [11]:
phone_data.describe()

,Unnamed: 0,battery_power,clock_speed,dual_sim,fc,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen
count,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1935.000000,1913.000000,1935.000000,1935.000000,1873.000000,1935.000000,1935.000000
mean,997.788114,1240.282687,1.528889,0.509044,4.298708,32.115245,0.504703,140.209819,4.529716,9.932817,646.829457,1255.708527,2120.500784,12.322997,5.757623,10.998398,0.762274,0.501809
std,577.034770,438.590972,0.820332,0.500047,4.345792,18.161480,0.292660,35.480487,2.285474,6.057774,445.042126,434.465962,1083.400626,4.209676,4.333399,5.457734,0.425801,0.500126
min,0.000000,501.000000,0.500000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,0.000000,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000
25%,499.500000,853.500000,0.700000,0.000000,1.000000,16.000000,0.200000,109.000000,3.000000,5.000000,284.500000,880.000000,1205.000000,9.000000,2.000000,6.000000,1.000000,0.000000
50%,999.000000,1231.000000,1.500000,1.000000,3.000000,32.000000,0.500000,141.000000,4.000000,10.000000,567.000000,1251.000000,2131.000000,12.000000,5.000000,11.000000,1.000000,1.000000
75%,1493.500000,1617.000000,2.250000,1.000000,7.000000,48.000000,0.800000,170.000000,7.000000,15.000000,948.000000,1638.500000,3056.000000,16.000000,9.000000,16.000000,1.000000,1.000000
max,1999.000000,1998.000000,4.000000,1.000000,19.000000,64.000000,2.000000,200.000000,8.000000,20.000000,1960.000000,2298.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000

## Podział na zbiory

In [20]:
X = phone_data.drop(["price_range", "Unnamed: 0"], axis=1)
Y = phone_data["price_range"]

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

## Preprocessing

In [17]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1935 entries, 0 to 1934
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     1935 non-null   int64
 1   battery_power  1935 non-null   int64
 2   blue           1915 non-null   object
 3   clock_speed    1935 non-null   float64
 4   dual_sim       1935 non-null   int64
 5   fc             1935 non-null   int64
 6   four_g         1935 non-null   object
 7   int_memory     1935 non-null   int64
 8   m_dep          1935 non-null   float64
 9   mobile_wt      1935 non-null   int64
 10  n_cores        1935 non-null   int64
 11  pc             1935 non-null   int64
 12  px_height      1935 non-null   int64
 13  px_width       1935 non-null   int64
 14  ram            1913 non-null   float64
 15  sc_h           1935 non-null   int64
 16  sc_w           1935 non-null   int64
 17  talk_time      1873 non-null   float64
 18  three_g        1935 non-null   int64
 19  touch_screen   1935 non-null   int64
 20  wifi           1935 non-null   object
dtypes: float64(4), int64(14), object(3)
memory usage: 317.6+ KB

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
text_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('one_hot', OneHotEncoder(sparse_output=False))
])